### ISSUE TITLE
not an issue but... what ofxTimeline fork and OS / OF version are you running?

### ISSUE THREAD

**Issue by moebiussurfing** [lg3bass/ofxTLVMMControl#1]
Hey, I want to try your app in windows 10 and 0.9.8
Also I am looking for a working for of ofxTimeline... do you have working fork for this?

**Comment by lg3bass** [comment]
Hi Moebiussurfing, 

Unfortunately I'm not running Win.  Sorry can't help you there.   ofxTLVMMControl is very much custom to my VMMTimeline app.   Instead I created a [ofxTLDatGui](https://github.com/lg3bass/ofxTLDatGui) addon for ofxTimeline.  Have a look at this [https://github.com/lg3bass/ofxTLDatGui](https://github.com/lg3bass/ofxTLDatGui) and the basic-example inside.  Hopefully once you get ofxTimeline up and running then try to build the example.

I use my own fork of [ofxTimeline](https://github.com/lg3bass/ofxTimeline) which is a derivative of @leozimmerman version of [ofxTimeline](https://github.com/leozimmerman/ofxTimeline).  What was tremendously helpful for me was to start with Leo's [Sonoscopio](https://github.com/leozimmerman/Sonoscopio) app.... which i still refer to when I get stuck.   Sonoscopio is a pretty darn cool app! Thanks [Leonardo](https://github.com/leozimmerman).

I do have a clone_addons.sh script that I need to update first but that is a map to all the required addons for ofxTimeline.  I will try to update this and add to this archive.  Not sure how you would set this up on PC though.

**Comment by moebiussurfing** [comment]
ok! thanks for your reply. i am courious to see some screenshot or video from your app... Do you have any link ?
EDIT: ok sorry, i found your youtube channel
